services:
  redis:
    build:
      context: ./
      dockerfile: ./Dockerfile
    #image: optimiste/redis:latest
    image: optimiste/redis:3.0.0-debian
    container_name: redis-julien
    restart: unless-stopped
    volumes:
      - redis:/data
      - ./redis.conf:/etc/redis/redis.conf
      #- ./logs:/var/log/redis
    ports:
      - 6379:6379/tcp
    security_opt:
      - no-new-privileges:true

volumes:
  redis:

networks:
  default:
    name: redis-julien
