name: Docker Image CI

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: #ubuntu-latest
      - self-hosted
      - env-test-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show OS release
        run: cat /etc/os-release

      - name: Check Docker version
        run: docker --version

      - name: Check Docker Compose version
        run: docker compose version
        
      - name: Build the Docker image
        run: docker compose build #docker build . --file Dockerfile --tag julien-KB:$(date +%s)
        #run: docker compose build --build-arg BUILDKIT_SYNTAX=docker/dockerfile:1 --progress=plain --no-cache --security-opt seccomp=unconfined

      - name: List running Docker Compose projects
        run: docker compose ls

      - name: List folder
        run: pwd && ls -la
