name: Deploy Redis with Docker Compose

on:
  workflow_dispatch:

jobs:

  prepare:
    runs-on:
      - self-hosted
      - env-test-1
    outputs:
      target-dir: ~/julien-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create target directory
        run: mkdir -p ~/julien-test

      - name: Copy compose.yml and redis.conf
        run: cp $PWD/compose.yml ~/julien-test/. && cp $PWD/redis.conf ~/julien-test/.

  run:
    runs-on:
      - self-hosted
      - env-test-2
    needs: prepare
    steps:
      - name: Run Docker Compose
        run: |
          cd ~/julien-test
          docker compose up -d

  verify:
    runs-on:
      - self-hosted
      - env-test-1
    needs: run
    steps:
      - name: List only the started container
        run: docker ps --filter "name=redis-julien"

