name: Deploy Redis with Docker Compose

on:
  workflow_dispatch:

jobs:

  run:
    runs-on:
      - self-hosted
      - env-test-2

    steps:
      #- name: Checkout repository
        #uses: actions/checkout@v4

      - name: Create target directory et file 
        run: mkdir -p ~/julien-test && touch ~/julien-test/compose.yml

      - name: Copy compose.yml to ~/julien-test
        run: cp $PWD/compose.yml ~/julien-test/compose.yml

      - name: Run the Docker container with compose
        run: |
          cd ~/julien-test
          docker compose up -d

      - name: List only the started container
        run: docker ps --filter "name=redis-julien"
