name: Docker Pull & Run CI

on:
  workflow_dispatch:

jobs:

  pull:
    runs-on:
      - self-hosted
      - env-test-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull the Docker image
        run: docker pull ${{ vars.DOCKERHUB_USERNAME }}/redis:latest

  run:
    runs-on:
      - self-hosted
      - env-test-2
    needs: pull   # s'exécute après le pull
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the Docker container
        #run: docker run -d --name redis-test ${{ vars.DOCKERHUB_USERNAME }}/redis:latest
        run: docker compose -f /home/julien/redis/compose.yml up -d
        
      - name: List only the started container
        run: docker ps --filter "name=redis-test"
