name: Docker Run CI/CD

on:
  workflow_dispatch:

jobs:

  run:
    runs-on:
      - self-hosted
      - env-test-2
    #needs: pull   # s'exécute après le pull
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run the Docker container
        #run: docker run -d --name redis-test ${{ vars.DOCKERHUB_USERNAME }}/redis:latest
        run: docker compose -f $PWD/compose.yml up -d
        
      - name: List only the started container
        run: docker ps --filter "name=redis-test"
