name: Docker Image CI

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: #ubuntu-latest
      - self-hosted
      - env-test-1

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo docker build . --file Dockerfile --tag julien-KB:$(date +%s)
