name: Docker Build & Push CI/CD

on:
  workflow_dispatch:

jobs:

  build:
    runs-on:
      - self-hosted
      - env-test-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker compose build

  push:
    runs-on:
      - self-hosted
      - env-test-2
    needs: build
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push the Docker image
        run: docker push optimiste/redis:latest

  cleanup:
    runs-on:
      - self-hosted
      - env-test-1
    needs: push
    steps:
      - name: Remove the local Docker image
        run: docker rmi aaaa/redis:latest

      - name: Verify image removal
        run: |
          if docker images | grep -q "aaaa/redis"; then
            echo "Image still exists locally!"
            exit 1
          else
            echo "Image successfully removed locally."
          fi

  pull:
    runs-on:
      - self-hosted
      - env-test-2
    needs: cleanup
    steps:
      - name: Pull the Docker image from Docker Hub
        run: docker pull optimiste/redis:latest

      - name: List Docker images after pull
        run: docker images
