name: Docker Image CI

on:
  workflow_dispatch:


jobs:

  build:

    runs-on: #ubuntu-latest
      - self-hosted
      - runner-test

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: echo "Salut ..." #docker build . --file Dockerfile --tag my-image-name:$(date +%s)
